# Generated by Django 3.0.3 on 2020-04-03 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('phone', models.CharField(max_length=20, unique=True, verbose_name='phone')),
                ('username', models.CharField(max_length=20, null=True, verbose_name='username')),
                ('email', models.CharField(max_length=20, null=True, verbose_name='email')),
                ('app_id', models.CharField(max_length=20, verbose_name='app_id')),
                ('is_verify', models.BooleanField(default=False, verbose_name='is_verify')),
                ('tags', models.CharField(max_length=20, verbose_name='tags')),
                ('channel_id', models.IntegerField(null=True, verbose_name='channel_id')),
                ('likes', models.CharField(max_length=255, null=True, verbose_name='likes')),
                ('dislikes', models.CharField(max_length=255, null=True, verbose_name='dislikes')),
                ('active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
