# Generated by Django 3.0.3 on 2020-04-03 03:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='app_id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='channel_id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='dislikes',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_verify',
        ),
        migrations.RemoveField(
            model_name='user',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='user',
            name='tags',
        ),
    ]
