# Generated by Django 3.0.3 on 2020-04-03 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20200403_0901'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='Name',
            field=models.CharField(max_length=20, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_id',
            field=models.CharField(max_length=10, null=True, verbose_name='username'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=20, null=True, verbose_name='phone'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=20, unique=True, verbose_name='username'),
        ),
    ]
